const Map<String, Map<String, dynamic>> statusConfig = {
  'NEW': {
    'label': 'Yangi',
    'emoji': '🆕',
    'color': 0xFFf59e0b,
    'bg': 0xFFfef3c7,
  },
  'DRIVER_ASSIGNED': {
    'label': 'Tayinlangan',
    'emoji': '📌',
    'color': 0xFFd97706,
    'next': 'PICKED_UP',
    'nextLabel': '🏠 Olib ketdim',
  },
  'PICKED_UP': {
    'label': 'Olib ketilgan',
    'emoji': '📦',
    'color': 0xFF2563eb,
    'next': 'AT_FACILITY',
    'nextLabel': '🏭 Sexga olib keldim',
  },
  'AT_FACILITY': {
    'label': 'Sexda',
    'emoji': '🏭',
    'color': 0xFF7c3aed,
    'next': 'WASHING',
    'nextLabel': '🧼 Yuvishga o\'tkazish',
  },
  'WASHING': {
    'label': 'Yuvilmoqda',
    'emoji': '🧼',
    'color': 0xFF0891b2,
    'next': 'DRYING',
    'nextLabel': '☀️ Quritishga o\'tkazish',
  },
  'DRYING': {
    'label': 'Quritilmoqda',
    'emoji': '☀️',
    'color': 0xFF0284c7,
    'next': 'FINISHED',
    'nextLabel': '✨ Pardozga o\'tkazish',
  },
  'FINISHED': {
    'label': 'Pardozda',
    'emoji': '✨',
    'color': 0xFF9333ea,
    'next': 'READY_FOR_DELIVERY',
    'nextLabel': '📦 Qadoqlab topshirish',
  },
  'READY_FOR_DELIVERY': {
    'label': 'Yetkazishga tayyor',
    'emoji': '✅',
    'color': 0xFF059669,
    'next': 'OUT_FOR_DELIVERY',
    'nextLabel': '🚐 Yetkazishga chiqdim',
  },
  'OUT_FOR_DELIVERY': {
    'label': 'Yetkazilmoqda',
    'emoji': '🚐',
    'color': 0xFF16a34a,
    'next': 'DELIVERED',
    'nextLabel': '✅ Topshirdim',
  },
  'DELIVERED': {
    'label': 'Yetkazildi',
    'emoji': '✅',
    'color': 0xFF15803d,
  },
  'CANCELLED': {
    'label': 'Bekor',
    'emoji': '❌',
    'color': 0xFFdc2626,
  },
};
